### ISSUE TITLE
Question on drmModeSetPlane

### ISSUE THREAD

**Issue by Consti10** [jc-kynesim/drmu#1]
Hello,

I only recently figured out your development shifted from hello_drmprime to here.

I am still on the "old" hello_drmprime code modified a lot to measure decode to display latency, see:
https://forums.raspberrypi.com/viewtopic.php?p=2034337#p2034337
https://github.com/Consti10/hello_drmprime/tree/master/hello_drmprime

I have a quick question: Is it possible to simply "swap" the fb of a (video) plane with an async operation using drm/kms while leaving the rest (crtc, format, width, height, compose) intact ?

E.g. the following pseudo-code:
setup crtc, connector,...
```
if(first frame){
   drmModeSetPlane() (async not possible, seems to take more time than needed)
}else{
   //only modify the "fb" id of the previous plane, leave everything else untouched.
   drmModeAtomicReq *req= drmModeAtomicAlloc();
   drmModeAtomicAddProperty(req,de->setup.planeId,DRM_MODE_OBJECT_FB,da->fb_id);
   if(drmModeAtomicCommit(de->drm_fd, req,0/*DRM_MODE_PAGE_FLIP_ASYNC | DRM_MODE_ATOMIC_NONBLOCK*/ ,       NULL)!=0){
      std::cerr<<"Cannot perform drmModeAtomicCommit"<<strerror(errno)<<"\n";
}
}
```
Code that does (not yet) work:
https://github.com/Consti10/hello_drmprime/blob/9344b1da0870863f9980dbe8aa1a404d2ebab9f1/hello_drmprime/drmprime_out.cpp#L217

**Comment by jc-kynesim** [comment]
Short answer - yes. However the flip is going to happen at some time in the future and you can't Q another commit till it has completed.  If you are going down this path I strongly recommend that you give this (or some other) framework a look as I've sorted (nearly) all of those issues.

**Comment by jc-kynesim** [comment]
If I know that someone other than me actually uses this code then I'll improve my documentation (hah!) / comments and try to avoid API breaking changes in future.

**Comment by Consti10** [comment]
> Short answer - yes. However the flip is going to happen at some time in the future and you can't Q another commit till it has completed. If you are going down this path I strongly recommend that you give this (or some other) framework a look as I've sorted (nearly) all of those issues.

Is the "you can't queue another commit till it has completed" a rpi limitation or a limitation from drm ?
For example, imagine the following scenario:
The user plays back a live 120fps video on a 60fps screen. (This is "stupid" one might say but actually quite common in our project, since a lot of camera(s) have reduced latency only in higher fps modes. And similar to when competitive gamers tripple buffer their game to render it at multiples of the dispplay refresh time and then let the compser swap the latest rendered frame on each VSYNC).
In this case, every time the application has decoded a frame via ffmpeg, it probably wants to immediately commit it to the screen queue to be swapped at the next VSYNC- replacing any "previous" frame that might still be in a "committed" and not scanned out state.

I'd think by passing either `DRM_MODE_PAGE_FLIP_ASYNC` or `DRM_MODE_ATOMIC_NONBLOCK` one would have the previosly described effect - but these flags are from the jetson drm documentation, not pi [link](https://docs.nvidia.com/jetson/l4t-multimedia/group__direct__rendering__manager.html#gaf7cbcfbaf1decf92c6638af4adec39a2)

I think your library's goal is HDR & frame pacing (correct me if I'm wrong) which I am sure is something a lot of people are interested in / want to play with on the pi. However, I am not even thinking about frame pacing yet, as long as the pi 4 drm/kms driver adds roughly 1-2 frames of latency already on its own compared to a traditional "Flip buffer at VSYNC" (driver) model. (see my measurements at the rpi forum link).

**Comment by jc-kynesim** [comment]
The Qing thing is DRM - somewhere it documents it as returning EBUSY under those circumstances - it may depend on h/w whether you can flip on non-vsync boundaries.
My lib will (I think) in fact do what you want - yes it will only flip frames on vsync, but the commit code merges pending requests s.t. the final one is the one that actually happens (i.e. if you commit 4 frames in one vsync time then the 1st 3 will be released and the final one will be displayed).
There is some latency in the system as you have (1) the frame that is being displayed, (2) the next frame that is about to be displayed which was committed on the last vsync and will be displayed on the next vsync which (AFAIK) can't be changed, (3) the next frame Qed for display which will be overwritten by subsequent commits.
Now with careful timing frame (2) could be committed just before the next vsync which would cut latency - so far I haven't tried that as the closer you get to the next vsync the greater the chance of missing it altogether due to scheduling hiccups.
